/**
 *
 * @author Muhammad Anas
 */
package IDMPackage;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.*;

public class downloader extends javax.swing.JFrame implements ActionListener {

    static void downloadComplete() {

    }

    IDM idm;
    Thread thread;
    ProgressPanel progressPanel;
    JLabel label;
    public static JFrame downloaderFrame;

    /**
     * Creates new form downloader
     */
    public downloader() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        urlTextField = new javax.swing.JTextField();
        downloadButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 800, 800));
        setMaximumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.FlowLayout());

        jLabel1.setText("URL     ");
        getContentPane().add(jLabel1);

        urlTextField.setColumns(50);
        urlTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urlTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(urlTextField);

        downloadButton.setText("Save To");
        downloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadButtonActionPerformed(evt);
            }
        });
        getContentPane().add(downloadButton);

        setBounds(0, 0, 706, 323);
    }// </editor-fold>//GEN-END:initComponents

    private void downloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadButtonActionPerformed
//        System.setProperty("http.proxyHost", "192.168.10.50");
//        System.setProperty("http.proxyPort", "8080");
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = fileChooser.showSaveDialog(this);
        File file = fileChooser.getSelectedFile();
        System.out.println("directry: " + file.getPath());
        progressPanel = new ProgressPanel();
        try {
            idm = new IDM(urlTextField.getText(), progressPanel, file.getPath());
            System.out.println("Starting Executers");
            downloaderFrame.add(progressPanel);
            progressPanel.startThread(idm);
            progressPanel.setUrlTextField(urlTextField.getText());
            progressPanel.setOutputDirectory(file.getPath(), urlTextField.getText().substring(urlTextField.getText().lastIndexOf('/') + 1));
            urlTextField.setText("");
            downloaderFrame.repaint();
            downloaderFrame.setVisible(true);
        } catch (Exception e) {

        }


    }//GEN-LAST:event_downloadButtonActionPerformed

    private void urlTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urlTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urlTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(downloader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(downloader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(downloader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(downloader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                downloaderFrame = new downloader();//.setVisible(true);
                //   
                downloaderFrame.setVisible(true);
                //JScrollPane scrollPane = new JScrollPane(downloaderFrame);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton downloadButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField urlTextField;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {

    }
}
