/**
 *
 * @author Parkash Kumar
 */
package IDMPackage;

public class ProgressPanel extends javax.swing.JPanel {

    Thread thread;
    String outputDirectory;
    private String outputFile;

    /**
     * Creates new form ProgressPanel
     */
    public ProgressPanel() {
        initComponents();
    }

    public void setProgressValue(int value) {
        progressBar.setValue(value);

        if (progressBar.getPercentComplete() == 1.0) {
            System.out.println("FINISHED");

            DownloadCompleteFrame dcf = new DownloadCompleteFrame(outputDirectory, urlTextField.getText(), outputFile);
            downloader.downloaderFrame.repaint();
            downloader.downloaderFrame.setVisible(true);      
        }
    }

    public void setUrlTextField(String url) {
        urlTextField.setText(url);
    }

    public void startThread(IDM idm) {
        thread = new Thread(idm);
        thread.start();
    }

    public void stopThread() {
        this.thread.stop();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        pauseButton = new javax.swing.JButton();
        resumeButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        urlTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setMaximumSize(new java.awt.Dimension(800, 300));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Progress");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 49, -1, 23));

        progressBar.setForeground(new java.awt.Color(102, 255, 102));
        progressBar.setStringPainted(true);
        add(progressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 49, 410, 23));

        pauseButton.setText("Pause");
        pauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseButtonActionPerformed(evt);
            }
        });
        add(pauseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        resumeButton.setText("Resume");
        resumeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resumeButtonActionPerformed(evt);
            }
        });
        add(resumeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        jLabel3.setText("URL      ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 42, 27));

        urlTextField.setEditable(false);
        urlTextField.setMaximumSize(new java.awt.Dimension(100, 20));
        urlTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urlTextFieldActionPerformed(evt);
            }
        });
        add(urlTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 11, 410, 27));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 122, 500, 20));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 500, 0));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 400, 90));
    }// </editor-fold>//GEN-END:initComponents

    private void urlTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urlTextFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_urlTextFieldActionPerformed

    private void pauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseButtonActionPerformed
        // TODO add your handling code here:
        //Thread.interrupted();
        this.thread.suspend();
    }//GEN-LAST:event_pauseButtonActionPerformed

    private void resumeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resumeButtonActionPerformed
        // TODO add your handling code here:

        this.thread.resume();

    }//GEN-LAST:event_resumeButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        stopThread();
        downloader.downloaderFrame.remove(this);
        downloader.downloaderFrame.repaint();
        downloader.downloaderFrame.setVisible(true);
    }//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton pauseButton;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JButton resumeButton;
    private javax.swing.JTextField urlTextField;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JTextArea jTextArea;

    void setTextToArea(int b, double c) {

        jTextArea1.append("Total Size :" + (float) b / 1024 + " kbs " + " : percentage:" + c + "%" + "\n");
    }

    void setOutputDirectory(String string, String file) {
        outputDirectory = string;
        outputFile = file;
    }
}
